/*
import { FooterContainer, FooterLogo, InfiniteScroll } from './StsFooter'

const LpFooter = () => {

    return (
        <>
            <FooterContainer>
                <InfiniteScroll>
                    <FooterLogo
                        src='src\assets\kerastaselogo.png'
                    />
                    <FooterLogo
                        src='src\assets\marimarialogo.png'
                    />
                    <FooterLogo
                        src='src\assets\kerastaselogo.png'
                    />
                    <FooterLogo
                        src='src\assets\brunatavareslogo.png'
                    />
                    <FooterLogo
                        src='src\assets\fran.png'
                    />
                    <FooterLogo
                        src='src\assets\lolalogo.png'
                    />
                    <FooterLogo
                        src='src\assets\kerastaselogo.png'
                    />
                    <FooterLogo
                        src='src\assets\marimarialogo.png'
                    />
                    <FooterLogo
                        src='src\assets\kerastaselogo.png'
                    />
                    <FooterLogo
                        src='src\assets\marimarialogo.png'
                    />
                    <FooterLogo
                        src='src\assets\kerastaselogo.png'
                    />
                    <FooterLogo
                        src='src\assets\brunatavareslogo.png'
                    />
                    <FooterLogo
                        src='src\assets\fran.png'
                    />
                    <FooterLogo
                        src='src\assets\lolalogo.png'
                    />
                </InfiniteScroll>
                <InfiniteScroll>
                    <FooterLogo
                        src='src\assets\kerastaselogo.png'
                    />
                    <FooterLogo
                        src='src\assets\marimarialogo.png'
                    />
                    <FooterLogo
                        src='src\assets\kerastaselogo.png'
                    />
                    <FooterLogo
                        src='src\assets\brunatavareslogo.png'
                    />
                    <FooterLogo
                        src='src\assets\fran.png'
                    />
                    <FooterLogo
                        src='src\assets\lolalogo.png'
                    />
                    <FooterLogo
                        src='src\assets\kerastaselogo.png'
                    />
                    <FooterLogo
                        src='src\assets\marimarialogo.png'
                    />
                    <FooterLogo
                        src='src\assets\kerastaselogo.png'
                    />
                    <FooterLogo
                        src='src\assets\marimarialogo.png'
                    />
                    <FooterLogo
                        src='src\assets\kerastaselogo.png'
                    />
                    <FooterLogo
                        src='src\assets\brunatavareslogo.png'
                    />
                    <FooterLogo
                        src='src\assets\fran.png'
                    />
                    <FooterLogo
                        src='src\assets\lolalogo.png'
                    />
                </InfiniteScroll>
            </FooterContainer>
        </>
    )
}

export default LpFooter 
*/